# This name will show up in the leader board of Mission Control
# https://missioncontrol.pseuco.com/#/leaderboard
team-name = "🧗‍♂️"

# The programming language you use: either "java" or "rust"
language = "java"

# Whether you implemented the bonus
bonus-implemented = false

# Instruct the testing framework to test your bonus implementation. This is
# only relevant for testing locally. In Mission Control, we will test both the
# regular version and the bonus if you set `bonus-implemented = true` above. The
# `CP_BONUS` environment variable overrides this setting.
test-bonus = false
