[package]
name = "spread-sim-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
spread-sim-core = { path = "../spread-sim-core" }
spread-sim-slug = { path = "../spread-sim-slug" }
spread-sim-rocket = { path = "../spread-sim-rocket" }